// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCyMYZYlpVWeWbFa4Je_LLHJ0_DpkRq8A',
    appId: '1:741867104589:web:4f1a7a72895f1c61d56f04',
    messagingSenderId: '741867104589',
    projectId: 'smart-move-2e56d',
    authDomain: 'smart-move-2e56d.firebaseapp.com',
    storageBucket: 'smart-move-2e56d.firebasestorage.app',
    measurementId: 'G-CTCTCCMM39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXL3DhB1Nco8DSmgJfg4VMrgtedkcK_Bg',
    appId: '1:741867104589:android:d4267f0f6923edb5d56f04',
    messagingSenderId: '741867104589',
    projectId: 'smart-move-2e56d',
    storageBucket: 'smart-move-2e56d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwIuy4AFffF_zeRFi8jKayguO8UmDf-zA',
    appId: '1:741867104589:ios:9e9a996dd3dc5cc2d56f04',
    messagingSenderId: '741867104589',
    projectId: 'smart-move-2e56d',
    storageBucket: 'smart-move-2e56d.firebasestorage.app',
    androidClientId: '741867104589-ott0m3ek8lbhkm8chvacc1ald99h4lpg.apps.googleusercontent.com',
    iosClientId: '741867104589-q4qc5afvkjqaehdf7old9f6im4h1evbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCyMYZYlpVWeWbFa4Je_LLHJ0_DpkRq8A',
    appId: '1:741867104589:web:b828340b12a40615d56f04',
    messagingSenderId: '741867104589',
    projectId: 'smart-move-2e56d',
    authDomain: 'smart-move-2e56d.firebaseapp.com',
    storageBucket: 'smart-move-2e56d.firebasestorage.app',
    measurementId: 'G-MCZ2ZWGPQR',
  );
}
